# Refrecnes:
# https://zespia.tw/blog/2015/01/21/continuous-deployment-to-github-with-travis/
# https://docs.travis-ci.com/user/languages/javascript-with-nodejs
# https://github.com/iissnan/theme-next-docs/blob/master/.travis.yml
# http://changyuheng.me/2015/when-hexo-static-site-meets-github-pages-and-travis-ci/

language: node_js
node_js: stable

cache:
  directories:
    - node_modules

before_install:
    - export TZ='Asia/Shanghai' # 更改时区

install:
  - npm install

before_script:
  - git submodule update --remote --merge

script:
  - hexo clean  #清除
  - hexo g  #生成

after_script:
  - git clone https://${GIT_PAGE_REF} .deploy_git  # GH_REF是最下面配置的仓库地址
  - cd .deploy_git
  - git checkout master
  - cd ../
  - mv .deploy_git/.git/ ./public/   # 这一步之前的操作是为了保留master分支的提交记录，不然每次git init的话只有1条commit
  - cd ./public
  - git config user.name "shdwaker"
  - git config user.email "525801713@qq.com"
  - git add .
  - git commit -m "Travis CI Auto Builder at `date +"%Y-%m-%d %H:%M"`"
  - git push --force --quiet "https://${GH_TOKEN}@${GIT_PAGE_REF}" master:master

branches:
  only:
    - master
env:
 global:
   - GIT_PAGE_REF: github.com/shdwaker/shdwaker.github.io.git
   - secure: "irce1XLgrV7MOwGY+PBcNUc8wS7qko63JKByN0d5E6o1Fh3yB3D6bondpkfgbBhW1q1Qy+ExFVwo0uOqLpTsp/TcJXuoTGUhZ0vBZ5EMTcm3dtiiJ7lfJ0kQTHSbdoG8HgNnXp+GrHzegVdPCEZ7gLPRREM6lkgB6JRXL4nbi4zDxMH7AwDzkmifxue/pfrBtGImDLrhNnLLoxMsN9aE5lJ0VH+BAPiVn62vv2PG1dnyBy6Tona56rNQX5cYhkNRwsBfExoQXjOPyryXWkoxaH1xJglP8GlnsEyi9kXZx6GVhZqISMZ/iDfeHaeuZ04wwk59Q0KmI6RrNWf1GavlkJ4kpzTWZDIBfV2VnJZvIujY5DgqcbH8RW6GnEnb0Kz17NkZbJ6xQiLJ+R1FRfJLK0ZD/WnLgtmfdBShXjsTh1hr5wqwY78VYQLA5tVd5uoEtY7Y1pFY++nNfc4uaKDRXEIuQY0VTL2+hq+9aRizNQx1GFk2U6dmrsu+uaB6q9+cgpdDzMn11dwsxwRGzena+kwEIx8NbWf8sNBp8LHuuZmqXsNa6lk0jVOegWV4q35gdGw556YbMv7HAlzPQ1siTdhySRifaWl3ZFis51hFT8qKLnQ4sO7q6HFsxEt6edfqtWBsJQXWVLwZDpv6MxVwtgzOuFNdo21M/FAMDnViZaI="

# configure notifications (email, IRC, campfire etc)
# please update this section to your needs!
# https://docs.travis-ci.com/user/notifications/
notifications:
  email:
    - ljc_8812@126.com
    - 525801713@qq.com
  on_success: change
  on_failure: always

